version: '3'
services:
  backend:
    image: localhost:5000/sal-backend:latest
    environment:
      SALESLOFT_URL_BASE: "https://api.salesloft.com"
      SALESLOFT_API_KEY: "${SALESLOFT_API_KEY}"
    networks:
      - test-network
    ports:
      - 8000:8000

  frontend:
    image: localhost:5000/sal-frontend:latest
    environment:
      BACKEND_HOST: "http://backend:8000"
    networks:
      - test-network
    ports:
      - 8080:8080
    depends_on:
      - backend
networks:
  test-network:
    driver: "bridge"