FROM golang:buster as builder

WORKDIR $GOPATH/src/
COPY . .

RUN go mod download

RUN go build -ldflags '-w -s -extldflags "-static"' -a -o /go/bin/frontend ./frontend

FROM debian:buster

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /go/bin/frontend /go/bin/frontend
COPY ./frontend/templates /go/bin/templates
COPY ./frontend/static /go/bin/static

ENV BACKEND_HOST="http://backend:8000"

ENTRYPOINT ["/go/bin/frontend"]